<?php
session_start();
include('db.php');
require('fpdf/fpdf.php');

// ✅ Allow only admin
if (!isset($_SESSION["email"]) || $_SESSION["is_admin"] !== true) {
    die("Access denied. Only admin can access this page.");
}

class PDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 10, 'Second Brain - Admin Summary Report', 0, 1, 'C');
        $this->Ln(5);
        $this->SetFont('Arial', '', 11);
        $this->Cell(0, 10, 'Generated on: ' . date('d M Y, h:i A'), 0, 1, 'C');
        $this->Ln(8);
        $this->Line(10, 28, 200, 28);
        $this->Ln(10);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by Admin | Page ' . $this->PageNo(), 0, 0, 'C');
    }
}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);

// ✅ Fetch total users and reminders
$total_users = $conn->query("SELECT COUNT(*) AS total FROM users")->fetch_assoc()['total'];
$total_reminders = $conn->query("SELECT COUNT(*) AS total FROM reminders")->fetch_assoc()['total'];

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, "System Overview", 0, 1);
$pdf->Ln(5);

$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 8, " Total Users: " . $total_users, 0, 1);
$pdf->Cell(0, 8, " Total Reminders: " . $total_reminders, 0, 1);
$pdf->Cell(0, 8, " Report Period: All Time", 0, 1);
$pdf->Ln(10);

// ✅ Section: User List Summary
$pdf->SetFont('Arial', 'B', 13);
$pdf->Cell(0, 8, "User Summary Table", 0, 1);
$pdf->Ln(5);

// Table header
$pdf->SetFillColor(31, 116, 231);
$pdf->SetTextColor(255);
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(10, 8, '#', 1, 0, 'C', true);
$pdf->Cell(45, 8, 'Name', 1, 0, 'C', true);
$pdf->Cell(70, 8, 'Email', 1, 0, 'C', true);
$pdf->Cell(50, 8, 'Total Reminders', 1, 1, 'C', true);

// Reset text color
$pdf->SetFont('Arial', '', 11);
$pdf->SetTextColor(0);

// ✅ Fetch all users with reminder counts
$query = "
    SELECT u.user_id, u.name, u.email, 
           COUNT(r.reminder_id) AS total_reminders
    FROM users u
    LEFT JOIN reminders r ON u.email = r.user_email
    GROUP BY u.user_id
    ORDER BY total_reminders DESC;
";

$result = $conn->query($query);
$count = 1;

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $pdf->Cell(10, 8, $count++, 1, 0, 'C');
        $pdf->Cell(45, 8, $row['name'], 1, 0, 'L');
        $pdf->Cell(70, 8, $row['email'], 1, 0, 'L');
        $pdf->Cell(50, 8, $row['total_reminders'], 1, 1, 'C');
    }
} else {
    $pdf->Cell(0, 8, 'No users found in the system.', 1, 1, 'C');
}

// ✅ Output the report
$pdf->Output('D', 'Admin_Summary_Report.pdf');
exit;
?>
