<?php
session_start();
include('db.php');
require('fpdf/fpdf.php');

// ✅ Check login
if (!isset($_SESSION["email"])) {
    die("Access denied. Please login.");
}

$email = $_SESSION["email"];

// ✅ Fetch user info
$stmt = $conn->prepare("SELECT name, email, phone FROM users WHERE email = ?");
$stmt->bind_param("s", $email);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("User not found.");
}

$user = $result->fetch_assoc();

// ✅ Fetch reminders
$rem_query = $conn->prepare("
    SELECT title, description, reminder_date, reminder_time, voice_file 
    FROM reminders 
    WHERE user_email = ?
    ORDER BY reminder_date DESC, reminder_time DESC
");
$rem_query->bind_param("s", $email);
$rem_query->execute();
$rem_result = $rem_query->get_result();

// ✅ Create PDF with custom header/footer
class PDF extends FPDF {
    function Header() {
        // Logo
        if (file_exists('logo.jpg')) {
            $this->Image('logo.jpg', 10, 8, 20);
        }
        // Title
        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor(31, 116, 231);
        $this->Cell(40); // Move right
        $this->Cell(110, 10, 'SECOND BRAIN - USER REPORT', 0, 1, 'C');
        $this->Ln(5);
        $this->SetDrawColor(31, 116, 231);
        $this->Line(10, 25, 200, 25);
        $this->Ln(8);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 10, 'Generated by Second Brain © 2025', 0, 0, 'C');
    }

    // User info box
    function UserInfo($user) {
        $this->SetFont('Arial', 'B', 13);
        $this->SetFillColor(240, 248, 255);
        $this->Cell(0, 10, 'User Information', 1, 1, 'C', true);
        $this->Ln(4);

        $this->SetFont('Arial', '', 12);
        $this->Cell(50, 8, 'Name:', 0, 0);
        $this->Cell(100, 8, $user['name'], 0, 1);
        $this->Cell(50, 8, 'Email:', 0, 0);
        $this->Cell(100, 8, $user['email'], 0, 1);
        $this->Cell(50, 8, 'Phone:', 0, 0);
        $this->Cell(100, 8, $user['phone'], 0, 1);
        $this->Cell(50, 8, 'Generated on:', 0, 0);
        $this->Cell(100, 8, date('d-m-Y H:i:s'), 0, 1);
        $this->Ln(6);
    }

    // Reminders Table
    function ReminderTable($result) {
        $this->SetFont('Arial', 'B', 12);
        $this->SetFillColor(31, 116, 231);
        $this->SetTextColor(255);
        $this->Cell(10, 10, '#', 1, 0, 'C', true);
        $this->Cell(40, 10, 'Title', 1, 0, 'C', true);
        $this->Cell(60, 10, 'Description', 1, 0, 'C', true);
        $this->Cell(30, 10, 'Date', 1, 0, 'C', true);
        $this->Cell(20, 10, 'Time', 1, 0, 'C', true);
        $this->Cell(30, 10, 'Voice Note', 1, 1, 'C', true);

        $this->SetFont('Arial', '', 11);
        $this->SetTextColor(0);
        $count = 1;
        while ($row = $result->fetch_assoc()) {
            $this->Cell(10, 10, $count, 1, 0, 'C');
            $this->Cell(40, 10, substr($row['title'], 0, 25), 1);
            $this->Cell(60, 10, substr($row['description'], 0, 40), 1);
            $this->Cell(30, 10, $row['reminder_date'], 1, 0, 'C');
            $this->Cell(20, 10, $row['reminder_time'], 1, 0, 'C');
            $this->Cell(30, 10, (!empty($row['voice_file']) ? 'Yes' : 'No'), 1, 1, 'C');
            $count++;
        }

        if ($count === 1) {
            $this->Cell(0, 10, 'No reminders found.', 1, 1, 'C');
        }
    }
}

// ✅ Generate PDF
$pdf = new PDF();
$pdf->AddPage();
$pdf->UserInfo($user);
$pdf->ReminderTable($rem_result);
$pdf->Output('I', 'SecondBrain_Report_' . preg_replace('/[^A-Za-z0-9]/', '_', $user['name']) . '.pdf');
exit;
?>
